In [2]:
import torch
import numpy as np

In Pytorch torch.Tensor is a multi-dimensional matrix conataining elements of a single data type
Default data type of float32
More suitable for deep learning than numpy array

In [4]:
my_list= [[1,2,3,4,5],["abc",3]]
my_list

[[1, 2, 3, 4, 5], ['abc', 3]]

Numpy array


In [6]:
np1= np.random.rand(3,4)
np1

array([[0.59276639, 0.59699818, 0.90400294, 0.81976348],
       [0.19755957, 0.41170095, 0.90440188, 0.55029949],
       [0.05247137, 0.1209005 , 0.87556811, 0.94371993]])

Tensors

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5574, -0.5822,  0.2460,  0.3274],
        [ 0.8122, -0.3945,  0.3663,  0.7835],
        [-0.2425, -0.8349, -1.2872, -1.5773]])

In [9]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.5819, -1.5540,  0.6533,  0.5492],
         [ 1.6604, -0.4835, -0.6831, -0.5467],
         [ 0.8930,  1.3918, -0.2496, -1.4162]],

        [[ 0.9358,  0.6749,  0.5508, -0.0251],
         [ 0.1679, -0.7675,  1.2881, -0.2587],
         [-0.0083,  1.1296,  0.2192, -1.3052]]])

In [10]:
## Create tensor out of numpy array
my_tensor= torch.tensor(np1)
my_tensor

tensor([[0.5928, 0.5970, 0.9040, 0.8198],
        [0.1976, 0.4117, 0.9044, 0.5503],
        [0.0525, 0.1209, 0.8756, 0.9437]], dtype=torch.float64)

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# reshape and view
my_torch =my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
#Reshape if we don't know the number of items
my_torch2= torch.arange(15)
my_torch2= my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [20]:
my_torch3= torch.arange(10)
my_torch3= my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Check difference betweeen view and reshape
with reshape and view they will corresponding tensors with respect to original tensors


In [26]:
my_torch5= torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_torch6= my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5[1]=4233
my_torch5


tensor([[   0, 4233,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [30]:
my_torch6

tensor([[   0, 4233,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

Grab as specific item

In [34]:
my_torch6[1,1]

tensor(6)

Grab a slice

In [39]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [41]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [43]:
#return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Tensor Math Operations