In [1]:
import torch
import numpy as np

In [2]:
tensor_a =torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [3]:
#addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
#subtraction
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [8]:
#multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
#Division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [13]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [14]:
#exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])